version: '3.8'

services:
  duckduckgo-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - LOG_LEVEL=info
      - REQUIRE_AUTH=false
      - RATE_LIMIT_PER_MINUTE=60
      - CACHE_TTL_SECONDS=300
      - MAX_SEARCH_RESULTS=20
      - REQUEST_TIMEOUT_SECONDS=30
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s