# 测试配置文件
# 用于测试环境的配置

[server]
host = "127.0.0.1"
port = 0  # 让系统自动选择端口
workers = 2
max_connections = 100
timeout = 10
max_request_size = 1048576  # 1MB
compression = true
https_enabled = false

[cache]
enabled = true
cache_type = "lru"
ttl = 60
max_size = 100
key_prefix = "test:"

[security]
enabled = true
jwt_secret = "test-secret-key-for-testing"
jwt_expiry = 3600
rate_limit = 1000
max_body_size = 1048576
api_key_enabled = true
api_key_prefix = "test"
strict_mode = false

[security.cors]
enabled = true
allow_origins = ["*"]
allow_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
allow_headers = ["*"]
allow_credentials = false
max_age = 3600

[security.rate_limiting]
algorithm = "token_bucket"
global_limit = 10000
whitelist = ["127.0.0.1", "::1"]
error_message = "Rate limit exceeded in test"

[security.api_keys]
test_key = { name = "Test Key", permissions = ["read", "write"], rate_limit = 1000 }
admin_key = { name = "Admin Key", permissions = ["read", "write", "admin"], rate_limit = 2000 }

[logging]
level = "debug"
format = "text"
stdout = true
stderr = false

[metrics]
enabled = true
port = 0  # 让系统自动选择端口
path = "/metrics"
interval = 5
prometheus_enabled = true
detailed_metrics = true

[monitoring]
health_check_interval = 10
performance_monitoring = true
error_tracking = true
request_tracing = true

[validation]
max_json_size = 1048576
max_schema_size = 1048576
strict_mode = false
custom_formats = false
timeout = 1000
max_concurrent = 50
cache_validation = true
detailed_errors = true

[performance.basic]
connection_pool_size = 5
request_queue_size = 50
enable_compression = true
compression_level = 1
enable_caching = true

[performance.optimized]
max_concurrent_requests = 100
connection_pool_size = 5
cache_size = 100
memory_limit_mb = 128
request_timeout = 10
enable_memory_pool = true
enable_connection_reuse = true
enable_compression = true

[performance.memory]
memory_limit_mb = 128
enable_memory_pool = true
memory_pool_size = 100
enable_gc_optimization = false
allocation_strategy = "simple"

[performance.concurrency]
max_concurrent_requests = 100
worker_threads = 2
request_timeout_secs = 10
enable_connection_reuse = true
enable_async_processing = true

[performance.cache_optimization]
cache_warmup = false
eviction_policy = "lru"
enable_cache_compression = false
cache_sharding = false
cache_shards = 2

[deployment]
environment = "test"
debug_mode = true
hot_reload = false
graceful_shutdown = true
shutdown_timeout = 5

[database]
enabled = false

[redis]
enabled = false

[notifications]
enabled = false

[backup]
enabled = false

[audit]
enabled = false