name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy, rustfmt
    
    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          duckduckgo-mcp-server/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('duckduckgo-mcp-server/Cargo.lock') }}
    
    - name: Check formatting
      run: |
        cd duckduckgo-mcp-server
        cargo fmt --all -- --check
    
    - name: Run clippy
      run: |
        cd duckduckgo-mcp-server
        cargo clippy --all-targets --all-features -- -D warnings
    
    - name: Run tests
      run: |
        cd duckduckgo-mcp-server
        cargo test --verbose
    
    - name: Build
      run: |
        cd duckduckgo-mcp-server
        cargo build --release --verbose

  security:
    name: Security audit
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Install cargo-audit
      run: cargo install cargo-audit
    
    - name: Run security audit
      run: |
        cd duckduckgo-mcp-server
        cargo audit