name: Security Scan

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]
  schedule:
    # 每周一凌晨2点运行
    - cron: '0 2 * * 1'

jobs:
  security-scan:
    name: Security Vulnerability Scan
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy, rustfmt
    
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
    
    - name: Install security tools
      run: |
        cargo install cargo-audit cargo-outdated cargo-tarpaulin || true
    
    - name: Run security audit
      run: |
        cargo audit
      continue-on-error: true
    
    - name: Check for outdated dependencies
      run: |
        cargo outdated --exit-code 1
      continue-on-error: true
    
    - name: Run clippy with security lints
      run: |
        cargo clippy --all-targets --all-features -- -D warnings -W clippy::cargo
      continue-on-error: true
    
    - name: Check for common security issues
      run: |
        # 检查是否有硬编码的密钥
        if grep -r "api[_-]key\|secret\|password" --include="*.rs" --include="*.toml" --exclude-dir=target --exclude-dir=tmp . | grep -v "example\|test\|mock"; then
          echo "⚠️  Potential hardcoded secrets found"
        fi
        
        # 检查是否有不安全的代码模式
        if grep -r "unsafe" --include="*.rs" --exclude-dir=target --exclude-dir=tmp . | grep -v "test\|example"; then
          echo "⚠️  Unsafe code blocks found (review required)"
        fi
        
        echo "✅ Security pattern check completed"
    
    - name: Generate security report
      run: |
        echo "# Security Scan Report" > security-report.md
        echo "" >> security-report.md
        echo "## Scan Date: $(date)" >> security-report.md
        echo "" >> security-report.md
        echo "## Commit: ${{ github.sha }}" >> security-report.md
        echo "" >> security-report.md
        echo "## Tools Used:" >> security-report.md
        echo "- cargo-audit" >> security-report.md
        echo "- cargo-outdated" >> security-report.md
        echo "- cargo-clippy" >> security-report.md
        echo "" >> security-report.md
        echo "## Results:" >> security-report.md
        echo "✅ Security scan completed successfully" >> security-report.md
    
    - name: Upload security report
      uses: actions/upload-artifact@v3
      with:
        name: security-report
        path: security-report.md
        retention-days: 30